#!/usr/bin/env bash
set -u

mode=${1:-zellij}

printf '%s\n' "Atalhos do mux ($mode)"
printf '%s\n' '  Alt+t       nova aba'
printf '%s\n' '  Alt+n       novo painel'
printf '%s\n' '  Alt+Enter   painel lateral'
printf '%s\n' '  Alt+setas   mover foco'
printf '%s\n' '  Alt+Space   tela cheia'
printf '%s\n' '  Alt+s       gerenciar sessoes'
printf '%s\n' '  F1          esta ajuda'

if [ "${MUX_HELP_WAIT:-0}" = 1 ]; then
    printf '\nPressione Enter para fechar...'
    read -r _
fi
